services:

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    # Disable access from localhost. Use Caddy instead
    # ports:
    #   - 27017:27017
    env_file:
      - .env
#   MongoDB env's listed in ./backend/.env 
#   Docker compose automatically pick up it from there:
#     MONGO_INITDB_ROOT_USERNAME
#     MONGO_INITDB_ROOT_PASSWORD
#     MONGO_INITDB_DATABASE
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "./Caddyfile.dev:/etc/caddy/Caddyfile"
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Disable access from localhost. Use Caddy instead
    # ports:
    #   - "8080:8080"
    expose:
      - 8080
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REACT_APP_NODE_ENV=development
    command: npm run start
    networks:
      - app-network

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 3005
    # Disable access from localhost. Use Caddy instead
    # ports:
    #   - 3005:3005
    command: node app.js
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REACT_APP_NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - mongo

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./DozzleUsers.yml:/data/users.yml
    expose:
      - 3001
    # Убираем прямое проксирование порта, так как будем использовать Caddy
    # ports:
    #   - 3001:3001
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_ADDR: :3001
      DOZZLE_HOSTNAME: dev-stat.probaland.ru
    networks:
      - app-network

volumes:
  mongo-data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
