services:

  # mongo:
  #   # image: mongo:4.2.4
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   env_file:
  #     - path: ./backend/.env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  #   networks:
  #     - app-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    command: npm run start
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
