# Dockerfile created by
# https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
# Only for test purposes

# This file don't install mongodb
# Need to start mongodb separately
# Cant connect to mongoDB after all

FROM node:20
WORKDIR /usr/src/app
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm ci --omit=dev
COPY . .
EXPOSE 3005
CMD ["node", "app.js"]