name: After Dev Test

on:
  workflow_run:
    # Имя должно совпадать с именем workflow в dev-test.yml
    workflows: ["Docker Compose Test"]  
    types:
      - completed

jobs:
  after-test:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v3
      
      - name: Проверка статуса предыдущего workflow
        run: |
          echo "Предыдущий workflow завершился со статусом: ${{ github.event.workflow_run.conclusion }}"
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "Предыдущий workflow завершился с ошибкой, прерываем выполнение"
            exit 1
          fi
      
      # Команды после успешного выполнения dev-test
      - name: Пример действия после dev-test
        run: |
          echo "Этот Action запускается после успешного выполнения dev-test"
