name: Docker Compose Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  # dev-test:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Проверка репозитория
  #       uses: actions/checkout@v3
      
  #     - name: Настройка Docker Buildx
  #       uses: docker/setup-buildx-action@v2
      
  #     - name: Создание .env файла через make и проверка
  #       run: |
  #         make prepare-debian
  #         cat .env
      
  #     - name: Проверка env-данных в контейнерах
  #       run: docker compose -f docker-compose.dev.yml config
      
  #     - name: Сборка контейнеров
  #       run: docker compose -f docker-compose.dev.yml build
      
  #     - name: Запуск контейнеров
  #       run: |
  #         docker compose -f docker-compose.dev.yml up -d
  #         echo "Даем время на запуск всех сервисов в контейнерах"
  #         sleep 20  
      
  #     - name: Проверка статуса контейнеров
  #       run: |
  #         docker compose -f docker-compose.dev.yml ps
          
  #         echo "Проверяем, что все контейнеры запущены"
  #         if [ $(docker compose -f docker-compose.dev.yml ps -q | wc -l) -ne $(docker compose -f docker-compose.dev.yml config --services | wc -l) ]; then
  #           echo "Не все контейнеры запущены!"
  #           docker compose -f docker-compose.dev.yml logs
  #           exit 1
  #         fi
      
  #     - name: Проверка доступности сервисов
  #       run: |
  #         echo "Проверка доступности бэкенда"
  #         docker compose -f docker-compose.dev.yml exec -T backend curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3005/
          
  #         echo "Проверка доступности MongoDB"
  #         docker compose -f docker-compose.dev.yml exec -T mongo mongosh --eval "db.runCommand({ping:1})" --quiet
      
  #     - name: Остановка контейнеров
  #       run: docker compose -f docker-compose.dev.yml down
  #       if: always()  # Выполнять всегда, даже если предыдущие шаги завершились с ошибкой


  dev-update:
    runs-on: ubuntu-latest
    # needs: dev-test
    steps:
      - name: Выполнение команд SSH с помощью ключа
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: -----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEAwyTMQCTiYtLPcHtH4S8yRRpGicafoZc+5OcNn02OnCY1b7YcmoDncYTp+Js118Tt6fCzjv3tNOCqcO4JGfBdaUK3pgj4NsWkmggv6mpuntaj+bpDzoaTgVw1lzuew9CZqNZA8aaqEbRG6oUj4fN0OhowiOIaV9nX05CXcp3HofKdlHCltHHodg7NQQUQUe+tB3foiKVoVpwREkgREFw56LPdszJqeBXlYgh7RodYh4h7plnwHgemay2DnDKPrKVFx0DL9TEtKrDB9nMLZDtX3AuWyGEbHRU/O9Xe7hBZp/9hGyd6yOLlcDwaniVJBqS5OgRTdE657dkl1lYq9WQFSW/ByohPvltE8AtBHSeE6H9fYAYQ4Dx/4EINFgHsRRQrQkME7Ya9B7VBqw7AfoRhUIVmx4awmPRx25Uwx69QizsCS02R3oT/eYYHg0gGKLAnCqGFBMdF9XCBz1dr2f8qjkG3L4F2SrSgx0pSSScm85WBhw65LjgEoqhlaQGg7KVvX4AqPxwZ6WfbrvIRWDhBAeLH1LjAkiznJGb5WQwrR3lHk+HCKifUHqdqwVgeaj8oSZr6/slag93C6/dbOamIWY5C+WsOGqae3k4O0b/+Q6eWTsEQCqXa7Mqgj+L24xeBPrGiMVPU72pm0xjTDJqkcvuz0w65LCeTmJgb8y27fsAAAdQKNCP5yjQj+cAAAAHc3NoLXJzYQAAAgEAwyTMQCTiYtLPcHtH4S8yRRpGicafoZc+5OcNn02OnCY1b7YcmoDncYTp+Js118Tt6fCzjv3tNOCqcO4JGfBdaUK3pgj4NsWkmggv6mpuntaj+bpDzoaTgVw1l1zuew9CZqNZA8aaqEbRG6oUj4fN0OhowiOIaV9nX05CXcp3HofKdlHCltHHodg7NQQUQUe+tB3foiKVoVpwREkgREFw56LPdszJqeBXlYgh7RodYh4h7plnwHgemay2DnDKPrKVFx0DL9TEtKrDB9nMLZDtX3AuWyGEbHRU/O9Xe7hBZp/9hGyd6yOLlcDwaniVJBqS5OgRTdE657dkl1lYq9WQFSW/ByohPvltE8AtBHSeE6H9fYAYQ4Dx/4EINFgHsRRQrQkME7Ya9B7VBqw7AfoRhUIVmx4awmPRx25Uwx69QizsCS02R3oT/eYYHg0gGKLAnCqGFBMdF9XCBz1dr2f8qjkG3L4F2SrSgx0pSSScm85WBhw65LjgEoqhlaQGg7KVvX4AqPxwZ6WfbrvIRWDhBAeLH1LjAkiznJGb5WQwrR3lHk+HCKifUHqdqwVgeaj8oSZr6/slag93C6/dbOamIWY5C+WsOGqae3k4O0b/+Q6eWTsEQCqXa7Mqgj+L24xeBPrGiMVPU72pm0xjTDJqkcvuz0w65LCeTmJgb8y27fsAAAADAQABAAACAB4Nk7spMwg/KR1MjyRZ7WcBBe3//eOX9GKyRsHK4vSfWclrhXox8fLkolfcJ22kcXN+01hpONfU5crgjdxFzU0BrmDOrtNYmuHx8tcqLwEdU0GJcxniVeMtPT+jW0Luda5y56mSM41I4rlc9y+nnYXX1RJZAJAh1jyyQ7xICxJTnVWdf9dUVWdScsPWbfwjvXXlx+QjaWHhGLsbe/GnFmlGBKdqIICeAT8RKRBn3jCXLWiejYDxvtyx4ZPVwP/o5tcZa705ClY8mi6iVzSJRlVVZH46ajd9rv0JKzLtjHzulM+JHsTww3V7skrjaSyXPxort0aBu42mC8LXSrWj/T1PYFxcZqY5gJyxaWdCrRWDucA+ZduZ1cxkJ+n7M7s+Cid264Xqz+afsTNjyU/qkrnVteujj32X99b3Gm0eBnVYLqjQf5NCBmeDQkSbVrXXhuzJunzzGLvDwgSOvALYYgJeGLhkkmf0ZjsySATe+CtpyTTeOtGFyxkKCncRJI8jDctEMl9iKNsoC86GHHmfafwwwA63TcphErus3MdzlAXo7a2BXXgZU2y7gGKL1jY3KcRiF37bSslBuU8Kt2fX1pHPxDYkpN/PHcHVUlnUto85rKXGOVrXlKZMkRbMafxofC5Y5vVg+46qQ47wYmLJm2xIMZiUGB6PgjgUU4vTBh3JAAABAQCSHwS14zOPx3gzVJ5R1jHzPJHXQ/p9cdOhnqZvBNUwYAbOlFvDidZIMbmTRC0+nVjvAU1fI7yQCvGzSVdbY4IFv5294HBgOvE9oRorraL8VWycIS/UL3Gpy0yFy8Iy6Ue9MTBdT+iaX5LBaNTBiy51jAF1mZdcdrVjdq4mtyaQ6Bf5l9cgQsoPBvC2siRZ9TaFgRrlPbmwRYGUY3wKPVTFjT3AvlLUyIkosdKWrbg9Vcl3CHvW0YSTQm5/OmfxO6IOwv8xt8oklmlKd1rFGV12n7QKxx+Uvij3oKzp8i6314bDrpTzoFV7emJSOwXNVpWuAk7HZ6OgMIgQvYrOZi3wAAABAQD1KO0yrpgQoMhX/I7A1mfGSobK3LsdKeToxwpoeKggTkhhFKCkSe3cIuvZET2QlEHlPRBYBTrRG1rxW4HRRK3nEd/+VL0MEfGoX+4Zwh4nPO+PpskYFd5cDTVaAjVsHHgmr4z9tZKeDVtNyH6nPp2uDnG0YNZ2vi/YTWD/BM9fcD7GLCCLz1HB7xUXPsG5yhu3x1LQtS8UL/9gGPoHEQXRjgaeNpSfDs1dVSDe6CMwHJwVZ5dpfyjyiVwVmkfMkZD4DOk8fKxVZPKbPkrK7C0lQ0+B2ckPu3oaz7pAYDkA+UpNBQWEwuXbimqzAIbodf+PCmVl6mEPodf7hQwtGgadAAABAQDLxbdu3KH8IS7sKAWXQxAaHQmGOvMNvIg4N+CHckLDh0nRql9AcLsxbV2vW0kYO1TaVA5zuTnFDKNaKgZR0ayHsoRP+KdUX5o2a5DTgHGWGhNQJH6ObVgNVLuMcgkt/7rBlFm8vgnBzUHFGaQJuyu030qPRotWr9pMLML/du4jsSRFF5S6YctFSnkyoIA7OdGKk/NH9JyTBJjQz9c9r3sj+JMp/1O6isDGw211NNexXISzyBEHmgPSA45GBEdJWTvVH/ADLVq5emZEuL/vptV3x0FZnbFXsfgbtJyWBCxCe2izJpThtrhbW0wyX7j8ytmfSGEhrJg74/Ijs8q9UNd3AAAAFnp4QGN2NDYwOTc4NS5ub3ZhbG9jYWwBAgME-----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            ls -la
            cd ${{ secrets.PROJECT_PATH_DEV }}
            git reset --hard
            git pull origin dev