name: Prod Test & Prod Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prod-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v3
      
      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Создание .env файла через make
        run: |
          make prepare-debian
      
      - name: Сборка контейнеров
        run: docker compose -f docker-compose.yml build
      
      - name: Запуск контейнеров
        run: |
          make prod
          echo "Даем время на запуск всех сервисов в контейнерах"
          sleep 20  
      
      - name: Проверка статуса контейнеров
        run: |
          docker compose -f docker-compose.yml ps
          
          echo "Проверяем, что все контейнеры запущены"
          if [ $(docker compose -f docker-compose.yml ps -q | wc -l) -ne $(docker compose -f docker-compose.yml config --services | wc -l) ]; then
            echo "Не все контейнеры запущены!"
            docker compose -f docker-compose.yml logs
            exit 1
          fi
      
      - name: Проверка доступности сервисов
        run: |
          echo "Проверка доступности бэкенда"
          docker compose -f docker-compose.yml exec -T backend curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3005/
          
          echo "Проверка доступности MongoDB"
          docker compose -f docker-compose.yml exec -T mongo mongosh --eval "db.runCommand({ping:1})" --quiet
      
      - name: Остановка контейнеров
        run: docker compose -f docker-compose.yml down
        if: always()  # Выполнять всегда, даже если предыдущие шаги завершились с ошибкой


  prod-update:
    runs-on: ubuntu-latest
    needs: prod-test
    steps:
      - name: Выполнение команд SSH с помощью ключа
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/zx/movies-explorer-dockerized
            make down
            echo ""
            git reset --hard
            git switch main
            git reset --hard
            echo ""
            git pull
            echo ""
            make prod
            sleep 20
            echo ""
            docker compose -f docker-compose.yml ps
            echo "Проверяем, что все контейнеры запущены"
            if [ $(docker compose -f docker-compose.yml ps -q | wc -l) -ne $(docker compose -f docker-compose.yml config --services | wc -l) ]; then
              echo "Не все контейнеры запущены!"
              docker compose -f docker-compose.yml logs
              exit 1
            fi
            echo ""
            echo "Проверка доступности бэкенда"
            docker compose -f docker-compose.yml exec -T backend curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3005/
            echo ""
            echo "Проверка доступности MongoDB"
            docker compose -f docker-compose.yml exec -T mongo mongosh --eval "db.runCommand({ping:1})" --quiet